import json

with open('templates/index.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

sections = data['sections']

# ── 1. TRUST BAR: yellow star, ₹649 ─────────────────────────────────────────
trust_html = (
    '<style>\n'
    '  .pl-trust { background: linear-gradient(135deg, #1B5E56 0%, #1A4A44 100%); padding: 12px 16px; }\n'
    '  .pl-trust__inner { max-width: 1200px; margin: 0 auto; display: flex; align-items: center; justify-content: center; flex-wrap: wrap; gap: 8px 28px; }\n'
    '  .pl-trust__item { display: flex; align-items: center; gap: 7px; font-family: var(--font-body-family, \'Inter\', sans-serif); font-size: 13px; color: rgba(248,245,238,0.92); white-space: nowrap; }\n'
    '  .pl-trust__item svg { width: 16px; height: 16px; flex-shrink: 0; }\n'
    '  .pl-trust__item--green svg { color: #7DD3C0; }\n'
    '  .pl-trust__item--star svg { color: #FBBF24; fill: #FBBF24; }\n'
    '  .pl-trust__item strong { color: #FFFFFF; font-weight: 600; }\n'
    '  .pl-trust__star-val { color: #FBBF24 !important; font-weight: 700 !important; font-size: 14px; }\n'
    '  .pl-trust__divider { width: 1px; height: 18px; background: rgba(248,245,238,0.2); }\n'
    '  @media (max-width: 600px) { .pl-trust__divider { display: none; } .pl-trust__inner { gap: 6px 16px; } .pl-trust__item { font-size: 12px; } }\n'
    '</style>\n'
    '<div class="pl-trust" role="region" aria-label="Trust Indicators">\n'
    '  <div class="pl-trust__inner">\n'
    '    <div class="pl-trust__item pl-trust__item--green">\n'
    '      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>\n'
    '      <span><strong>5,200+</strong> Happy Customers</span>\n'
    '    </div>\n'
    '    <div class="pl-trust__divider"></div>\n'
    '    <div class="pl-trust__item pl-trust__item--star">\n'
    '      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#FBBF24" stroke="#FBBF24" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/></svg>\n'
    '      <span><span class="pl-trust__star-val">4.9&#9733;</span> Google Rating</span>\n'
    '    </div>\n'
    '    <div class="pl-trust__divider"></div>\n'
    '    <div class="pl-trust__item pl-trust__item--green">\n'
    '      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="1" y="3" width="15" height="13"/><polygon points="16 8 20 8 23 11 23 16 16 16 16 8"/><circle cx="5.5" cy="18.5" r="2.5"/><circle cx="18.5" cy="18.5" r="2.5"/></svg>\n'
    '      <span>Free Delivery <strong>above &#8377;649</strong></span>\n'
    '    </div>\n'
    '    <div class="pl-trust__divider"></div>\n'
    '    <div class="pl-trust__item pl-trust__item--green">\n'
    '      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>\n'
    '      <span>Farm-Direct from <strong>Idukki, Kerala</strong></span>\n'
    '    </div>\n'
    '  </div>\n'
    '</div>'
)
sections['custom_liquid_V7N698']['settings']['custom_liquid'] = trust_html

# ── 2. DELIVERY BAR: ₹649, richer design ─────────────────────────────────────
delivery_html = (
    '<style>\n'
    '  .pureleven-delivery { max-width: 1200px; margin: 0 auto; padding: 0 16px; box-sizing: border-box; }\n'
    '  .pureleven-delivery__inner {\n'
    '    display: flex; align-items: flex-start; gap: 16px;\n'
    '    background: linear-gradient(135deg, #E8F5F3 0%, #F0FAF8 100%);\n'
    '    border: 1.5px solid #B8DDD9;\n'
    '    border-radius: 14px;\n'
    '    padding: 20px 24px;\n'
    '    transition: box-shadow 0.3s ease, transform 0.3s ease;\n'
    '  }\n'
    '  .pureleven-delivery__inner:hover { box-shadow: 0 6px 20px rgba(27, 94, 86, 0.12); transform: translateY(-1px); }\n'
    '  .pureleven-delivery__icon {\n'
    '    flex-shrink: 0; width: 48px; height: 48px;\n'
    '    background: linear-gradient(135deg, #1B5E56, #4D9B93);\n'
    '    border-radius: 12px;\n'
    '    display: flex; align-items: center; justify-content: center;\n'
    '    margin-top: 2px;\n'
    '    box-shadow: 0 4px 12px rgba(27, 94, 86, 0.25);\n'
    '  }\n'
    '  .pureleven-delivery__icon svg { width: 22px; height: 22px; }\n'
    '  .pureleven-delivery__content { flex: 1; min-width: 0; }\n'
    '  .pureleven-delivery__title {\n'
    '    margin: 0 0 5px 0;\n'
    '    font-family: var(--font-heading-family, \'Playfair Display\', serif);\n'
    '    font-size: 17px; font-weight: 500; color: #1B3A30; line-height: 1.3; letter-spacing: 0.01em;\n'
    '  }\n'
    '  .pureleven-delivery__text {\n'
    '    margin: 0;\n'
    '    font-family: var(--font-body-family, \'Inter\', sans-serif);\n'
    '    font-size: 14px; font-weight: 400; color: #5A6B67; line-height: 1.6;\n'
    '  }\n'
    '  .pureleven-delivery__text span { font-weight: 600; color: #1B3A30; }\n'
    '  .pureleven-delivery__badge {\n'
    '    flex-shrink: 0; align-self: center;\n'
    '    background: #1B5E56; color: #FFFFFF;\n'
    '    font-family: var(--font-body-family, \'Inter\', sans-serif);\n'
    '    font-size: 12px; font-weight: 600; letter-spacing: 0.04em;\n'
    '    padding: 5px 12px; border-radius: 100px;\n'
    '    white-space: nowrap;\n'
    '  }\n'
    '  @media (max-width: 640px) {\n'
    '    .pureleven-delivery { padding: 0 12px; }\n'
    '    .pureleven-delivery__inner { padding: 16px; gap: 12px; }\n'
    '    .pureleven-delivery__icon { width: 40px; height: 40px; border-radius: 10px; }\n'
    '    .pureleven-delivery__icon svg { width: 18px; height: 18px; }\n'
    '    .pureleven-delivery__title { font-size: 15px; }\n'
    '    .pureleven-delivery__text { font-size: 13px; }\n'
    '    .pureleven-delivery__badge { display: none; }\n'
    '  }\n'
    '</style>\n'
    '<div class="pureleven-delivery">\n'
    '  <div class="pureleven-delivery__inner">\n'
    '    <div class="pureleven-delivery__icon">\n'
    '      <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">\n'
    '        <rect x="1" y="3" width="15" height="13"></rect>\n'
    '        <polygon points="16 8 20 8 23 11 23 16 16 16 16 8"></polygon>\n'
    '        <circle cx="5.5" cy="18.5" r="2.5"></circle>\n'
    '        <circle cx="18.5" cy="18.5" r="2.5"></circle>\n'
    '      </svg>\n'
    '    </div>\n'
    '    <div class="pureleven-delivery__content">\n'
    '      <p class="pureleven-delivery__title">Free Delivery &amp; Easy Returns</p>\n'
    '      <p class="pureleven-delivery__text">Free delivery on orders above <span>&#8377;649</span> across India. Delivered in <span>4\u20135 working days</span>. Returns within 7 days.</p>\n'
    '    </div>\n'
    '    <div class="pureleven-delivery__badge">FREE SHIP &#8377;649+</div>\n'
    '  </div>\n'
    '</div>'
)
sections['custom_liquid_nrxnGY']['settings']['custom_liquid'] = delivery_html

with open('templates/index.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Done — trust bar + delivery bar updated")
