#!/usr/bin/env bash
# scripts/05_go_live.sh
#
# Go-live helper script for Pureleven WhatsApp Commerce Intelligence OS.
# Validates env vars, starts the server, and installs the daily orchestrator cron.
#
# Usage (from anu-login/backend):
#   chmod +x scripts/05_go_live.sh
#   ./scripts/05_go_live.sh [--check-only] [--no-cron] [--port 8000]
#
# Options:
#   --check-only    Validate env only, don't start anything
#   --no-cron       Skip cron installation
#   --port PORT     uvicorn port (default 8000)
#
# Production deployment:
#   On the Linux server, use systemd (deploy/anu-login-backend.service)
#   instead of this script. This script is for local dev / staging.

set -euo pipefail

# ── Parse args ─────────────────────────────────────────────────────────────────
CHECK_ONLY=false
INSTALL_CRON=true
PORT=8000

while [[ $# -gt 0 ]]; do
  case "$1" in
    --check-only) CHECK_ONLY=true; shift ;;
    --no-cron)    INSTALL_CRON=false; shift ;;
    --port)       PORT="$2"; shift 2 ;;
    *)            echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ── Paths ──────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
VENV_PYTHON="${BACKEND_DIR}/../../.venv/bin/python"
VENV_UVICORN="${BACKEND_DIR}/../../.venv/bin/uvicorn"
ENV_FILE="${BACKEND_DIR}/.env"
CRON_SCRIPT="${SCRIPT_DIR}/daily_orchestrate.sh"

# ── Load .env ──────────────────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
  echo "✅  Loaded .env from $ENV_FILE"
else
  echo "⚠️   No .env file found at $ENV_FILE"
  echo "    Copy deploy/.env.example → .env and fill in values."
fi

# ── Validate env vars ──────────────────────────────────────────────────────────
echo ""
echo "── Environment validation ────────────────────────────────────────────"

MISSING=()

check_var() {
  local name="$1"
  local val="${!name:-}"
  if [[ -z "$val" ]]; then
    echo "  ❌  $name  (NOT SET)"
    MISSING+=("$name")
  else
    # Mask sensitive values
    case "$name" in
      *TOKEN*|*SECRET*|*KEY*)
        echo "  ✅  $name = ${val:0:6}…${val: -4}" ;;
      *)
        echo "  ✅  $name = $val" ;;
    esac
  fi
}

# Core
check_var "ANU_LOGIN_ADMIN_SECRET"

# Shopify
check_var "SHOPIFY_SHOP_DOMAIN"
check_var "SHOPIFY_ADMIN_API_TOKEN"
check_var "SHOPIFY_WEBHOOK_SECRET"

# Delhivery
check_var "DELHIVERY_API_TOKEN"
check_var "DELHIVERY_WEBHOOK_SECRET"

# Wabis
check_var "WABIS_API_KEY"
check_var "WABIS_BASE_URL"

# Public URL
check_var "PUBLIC_BASE_URL"

echo ""
if [[ ${#MISSING[@]} -gt 0 ]]; then
  echo "  ⚠️   ${#MISSING[@]} env vars not set: ${MISSING[*]}"
  echo "       Fill these in .env before going live in production."
  echo "       The server will start but some features will be disabled:"
  echo "        • WABIS_API_KEY missing     → messages send as dev stubs only"
  echo "        • SHOPIFY_WEBHOOK_SECRET missing → HMAC validation disabled (insecure!)"
  echo "        • DELHIVERY_WEBHOOK_SECRET missing → Delhivery HMAC validation disabled"
  echo ""
  if [[ "$CHECK_ONLY" == "true" ]]; then exit 1; fi
else
  echo "  🎉  All env vars are set!"
fi

if [[ "$CHECK_ONLY" == "true" ]]; then
  echo "  (--check-only mode, exiting without starting server)"
  exit 0
fi

# ── Validate Python imports ────────────────────────────────────────────────────
echo "── Import check ──────────────────────────────────────────────────────"
cd "$BACKEND_DIR"
ROUTE_COUNT=$("$VENV_PYTHON" -c "from app.main import app; print(len(app.routes))" 2>&1)
if [[ "$ROUTE_COUNT" =~ ^[0-9]+$ ]]; then
  echo "  ✅  App imports OK — $ROUTE_COUNT routes"
else
  echo "  ❌  Import failed:"
  echo "      $ROUTE_COUNT"
  exit 1
fi

# ── Install daily cron (10am IST = 4:30am UTC) ────────────────────────────────
if [[ "$INSTALL_CRON" == "true" ]]; then
  echo ""
  echo "── Daily orchestrator cron ───────────────────────────────────────────"

  # Write the cron helper script
  cat > "$CRON_SCRIPT" << CRONSCRIPT
#!/usr/bin/env bash
# Auto-generated by 05_go_live.sh — daily WhatsApp journey orchestrator
# Runs at 10:00am IST (4:30am UTC) every day

set -euo pipefail
source "${ENV_FILE:-/dev/null}" 2>/dev/null || true

SHOP="\${SHOPIFY_SHOP_DOMAIN:-rwxtic-gz.myshopify.com}"
BASE_URL="\${PUBLIC_BASE_URL:-http://localhost:${PORT}}"

LOG_FILE="${BACKEND_DIR}/logs/orchestrator_\$(date +%Y%m%d).log"
mkdir -p "${BACKEND_DIR}/logs"

echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting daily orchestration..." >> "\$LOG_FILE"

RESPONSE=\$(curl -s -X POST "\${BASE_URL}/api/journey/orchestrate" \\
  -H "Content-Type: application/json" \\
  -d '{"shop_domain":"'""\$SHOP"'"","dry_run":false}' \\
  --max-time 120)

echo "\$RESPONSE" >> "\$LOG_FILE"
echo "[\$(date -u +%Y-%m-%dT%H:%M:%SZ)] Done." >> "\$LOG_FILE"
CRONSCRIPT

  chmod +x "$CRON_SCRIPT"
  echo "  ✅  Cron script created: $CRON_SCRIPT"

  # Install crontab entry (macOS/Linux)
  CRON_LINE="30 4 * * * $CRON_SCRIPT  # Pureleven WhatsApp daily orchestrator"

  if crontab -l 2>/dev/null | grep -q "Pureleven WhatsApp daily orchestrator"; then
    echo "  ⏩  Cron already installed (skipping)"
  else
    (crontab -l 2>/dev/null || true; echo "$CRON_LINE") | crontab -
    echo "  ✅  Cron installed: 4:30am UTC daily (= 10:00am IST)"
    echo "      Verify with: crontab -l"
  fi

  echo ""
  echo "  📋  Linux systemd alternative (production servers):"
  echo "      sudo cp deploy/anu-login-backend.service /etc/systemd/system/"
  echo "      sudo systemctl daemon-reload && sudo systemctl enable anu-login-backend"
  echo "      Add a separate systemd timer for the orchestrator cron."
fi

# ── Start server ───────────────────────────────────────────────────────────────
echo ""
echo "── Starting server ───────────────────────────────────────────────────"
echo "  Port   : $PORT"
echo "  Workers: 1 (use --workers 4 for production)"
echo "  Reload : enabled (disable in production)"
echo ""
echo "  Press Ctrl+C to stop"
echo ""

exec "$VENV_UVICORN" app.main:app \
  --host 0.0.0.0 \
  --port "$PORT" \
  --reload \
  --log-level info
